version: '3'

services:
  database:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5432:5432'

  app:
    container_name: auth_service
    build: .
    ports:
      - '8000:8000'
    depends_on:
      database: