version: '3'  # Версия используемой схемы для Docker Compose

services:  # Определение сервисов, которые будут запущены
  database:  # Сервис базы данных
    container_name: postgres  # Имя контейнера для базы данных
    image: postgres  # Официальный образ PostgreSQL
    environment:  # Переменные окружения для настройки базы данных
      - POSTGRES_DB=${DB_NAME}  # Название базы данных
      - POSTGRES_USER=${DB_USER}  # Имя пользователя для базы данных
      - POSTGRES_PASSWORD=${DB_PASSWORD}  # Пароль для пользователя базы данных
    ports:
      - '5432:5432'  # Прокси-порты для доступа к базе данных

  app:  # Сервис приложения (например, Django)
    container_name: auth_service  # Имя контейнера для приложения
    build: .  # Строим контейнер из текущей директории
    ports:
      - '8000:8000'  # Прокси-порты для доступа к приложению
    depends_on:  # Сервис зависит от базы данных, будет запущен после неё
      database:  # Указывает, что сервис приложения зависит от базы данных
